load("@rules_python//python:defs.bzl", "py_binary", "py_library")

package(default_visibility = ["//visibility:public"])

exports_files([
    "__init__.py",
    "bot.py",
    "bundle.py",
    "export.py",
    "hardware_config.py",
    "main.py",
    "train.py",
])

# ------------------------------------------------------------------------------
# PyTorch Dependency Group (Core, JIT & Math dependencies)
# ------------------------------------------------------------------------------
py_library(
    name = "torch_deps",
    deps = [
        "@pip//filelock",
        "@pip//fsspec",
        "@pip//jinja2",
        "@pip//markupsafe",
        "@pip//mpmath",
        "@pip//networkx",
        "@pip//numpy",
        "@pip//sympy",
        "@pip//torch",
        "@pip//typing_extensions",
    ],
)

# ------------------------------------------------------------------------------
# Core Package Libraries and Binaries
# ------------------------------------------------------------------------------
py_library(
    name = "bot_lib",
    srcs = [
        "__init__.py",
        "bot.py",
    ],
    imports = [".."],
    deps = [
        ":torch_deps",
        "@pip//numpy",
        "@pip//rlbot",
        "@rules_python//python/runfiles",
    ],
)

py_binary(
    name = "bot_bin",
    srcs = ["bot.py"],
    data = ["//:bot_configs"],
    imports = [".."],
    main = "bot.py",
    deps = [":bot_lib"],
)

py_binary(
    name = "main",
    srcs = ["main.py"],
    imports = [".."],
    main = "main.py",
)

py_library(
    name = "hardware_config",
    srcs = ["hardware_config.py"],
    imports = [".."],
    deps = [
        ":torch_deps",
    ],
)

py_binary(
    name = "train",
    srcs = ["train.py"],
    data = ["//:collision_meshes"],
    imports = [".."],
    main = "train.py",
    deps = [
        ":hardware_config",
        ":torch_deps",
        "@pip//numpy",
        "@pip//rlgym_ppo",
        "@pip//rlgym_sim",
        "@pip//rocketsim",
    ],
)

py_binary(
    name = "export",
    srcs = ["export.py"],
    imports = [".."],
    main = "export.py",
    deps = [
        ":torch_deps",
    ],
)

py_binary(
    name = "bundle",
    srcs = ["bundle.py"],
    data = [
        "bot.py",
        "//:bot_configs",
    ],
    imports = [".."],
    main = "bundle.py",
)
